### ISSUE TITLE
Why use the query modifier for the queryAndRevert function?

### ISSUE THREAD

**Issue by Chocolatieee0929** [balancer/balancer-v3-monorepo#860]
## Question
This is the documentation's explanation of `queryAndRevert`.
> #  quoteAndRevert
> Since quote changes the Vault state some query combinations are not possible. For example, if you wanted to quote querySwapExactIn for POOL_A but also querySwapExactOut for POOL_A in its initial state, you would have to use quoteAndRevert. In this variant, the call always reverts and returns the result in the revert data (similar to the v2 mechanism).

`queryAndRevert` uses the `query` modifier to ensure it is a static call. Why is it necessary to use `revert`?

## Suggestion
Consider removing the `query` modifier.

**Comment by jubeira** [comment]
Hi @Chocolatieee0929,

You can see an example here: #323; we need the second query to start clean, which is why we revert the changes ([see these lines](https://github.com/balancer/balancer-v3-monorepo/pull/323/files#diff-adca64f9f73dfc114bdd62b6c123885bb9317b420ee1b018759c9e5f6f8a9922R48-R50)).

if you need a contract that performs more than one query in the same context, using regular queries the state will be affected after the first one. In the example above, the second query would be affected by the first one, which is what we want to prevent.

In any case it's still a query, and we want to ensure that the execution happens in a static context.

Does this answer your question?

**Comment by jubeira** [comment]
Closing; stale.
