### ISSUE TITLE
State Sharing Issue Between `onComputeDynamicSwapFeePercentage` and `onSwap`

### ISSUE THREAD

**Issue by andreiashu** [balancer/balancer-v3-monorepo#894]
While adapting the `FXPool`'s fee calculation to Balancer V3, I've identified a limitation in the current architecture:  `onComputeDynamicSwapFeePercentage` and `onSwap` functions do not share state.

This forces redundant calculations in both functions, particularly for complex fee structures like FXPool's, where fees depend on the swap amount and its effect on pool ratios.

The current dynamic swap fee percentage mechanism only supports basic rules due to this lack of state sharing.

I think that allowing the Vault to pass mutable state data between these functions could solve the immediate issue, but it may not be the most elegant solution.

Are there more efficient or cleaner approaches to handle complex, interdependent fee calculations in Balancer V3?

**Comment by andreiashu** [comment]
I'd like to add more context here: in the previous version of the FXPool (Bal V2) we would mint LP tokens as a proportion of the fee numeraire (equivalent value in USD). Minting LP tokens from a pool doesn't seem to be possible outside of the `initialize` or `addLiquidity` flow.

Hence the need to use `onComputeDynamicSwapFeePercentage` and the issue I stumbled on in the original description of this ticket

**Comment by jubeira** [comment]
Thanks for bringing this up @andreiashu.

`onComputeDynamicSwapFeePercentage` is designed to be simple and specific, which is why it's just a `view` function.
`onBeforeSwap` on the contrary is more generic: you can save state there if needed (transient storage might be a good idea if it's just to store an intermediary result) and even reenter the vault and trigger another operation (e.g. `addLiquidity`). That would allow you to mint LP tokens before swapping for example (or anything that you want; could also be even another swap).

> This forces redundant calculations in both functions, particularly for complex fee structures like FXPool's, where fees depend on the swap amount and its effect on pool ratios.

By any chance is there some draft we can look at? Is this redundancy overly complex or expensive in terms of gas costs?

> I think that allowing the Vault to pass mutable state data between these functions could solve the immediate issue, but it may not be the most elegant solution.

This is probably the case, although in terms of architecture a hook to compute a dynamic fee percentage passing data to the main swap hook sounds a bit weird to me.

**Comment by andreiashu** [comment]
@jubeira thanks for the suggestion, was focusing so much on trying to make `onComputeDynamicSwapFeePercentage` work for us that I forgot about `onBeforeSwap`.

I already have a working draft of this, will send you access to our repo by end of tomorrow. 

To help anyone that might stumble on this issue: at the time of writing transient storage is not yet available in the Solidity high level language, but you can use assembly. In OpenZeppelin and Balancer V3 there's helper libraries that I used to accomplish what I needed: `StorageSlotExtension` and `TransientStorageHelpers`.

**Comment by andreiashu** [comment]
hi @jubeira I sent you access to our repo (also for @EndymionJkb )
